Update of Data Generation to accept file-based input data
microsoft/glue pull request #11
Opened 2022-02-08 12:10 UTC by goergenj

2022-02-14 13:54 UTC, nonstoptimm requested changes

2022-02-14 13:57 UTC, goergenj commented on requirements.txt
> -scikit-learn==0.23.1
Don't know why "scikit-learn" has been marked as a change. It was already on this version in "main":
<img width="268" alt="image" src="https://user-images.githubusercontent.com/31212469/153877620-d341c0bb-0243-41ea-9574-7093d0b4792c.png">

2022-02-14 13:58 UTC, goergenj commented on requirements.txt
> -scikit-learn==0.23.1
I removed the version because I had issues running it with the version hard-coded. I can re-test this again.

2022-02-14 13:59 UTC, goergenj commented on notebooks/Data - Training Data Generator.ipynb
>    },
I can add the samples based on the "booking" example instead, if that is easier to understand.

2022-02-22 14:30 UTC, goergenj commented
@nonstoptimm When you have time, please double check the updates I did based on the last review and let me know, if we can merge.

2023-03-22 01:40 UTC, merged